version: '3.8'

services:
  apache_php:
    image: docker.io/daniel300x/php8.3-apache2.4:v2.0
    container_name: Apache-PHP
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - AraNetwork
    depends_on:
      - mysql
  mysql:
    image: docker.io/daniel300x/mysql-8.0:v1.0
    container_name: MySQL
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backup:/home/backup
    environment:
      MYSQL_ROOT_PASSWORD: HwWin10A.1
      MYSQL_DATABASE: ara_db
      MYSQL_USER: devmaster
      MYSQL_PASSWORD: dev123@
    networks:
      - AraNetwork
networks:
  AraNetwork:
    driver: bridge