# CRIANDO IMAGEM PARTINDO DO MySQL 8.4
FROM mysql:8.4

#CRIANDO SENHA DE ROOT E UMA NOVA BASE DE DADOS
ENV MYSQL_ROOT_PASSWORD=HwWin10A.1
ENV MYSQL_DATABASE=ara_db
ENV MYSQL_USER=AraNet
ENV MYSQL_PASSWORD=dev123@

WORKDIR /var/lib/mysql
COPY ./data/mysql /var/lib/mysql
COPY ./backup /home/backup


#HABILITANDO PORTA PADRÃO
EXPOSE 3306

#COMANDO DE INICIALIZAÇÃO DO CONTAINER MYSQL
CMD [ "mysqld" ]